name: Push Docker Image to DockerHub # Deploy
on:
  push:
    branches: [ main ]

jobs:
  docker-build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Create .env file
        run: |
          echo "REACT_APP_BASE_URL_LOCAL=https://rri-backend.mosipcmuafrica.me/api" > .env
          
      - 
        name: Display .env file
        run: cat .env
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest  ## Go to latest