
name: Push Docker Image to DockerHub
on:
  push:
    branches: [ main ]

jobs:
  docker-build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.CONTAINER_REGISTRY }}/rri-frontend
          build-args: |
            REACT_APP_CLIENT_ID=${{secrets.REACT_APP_CLIENT_ID}}
          